ci: update GitHub Actions workflows for improved CI/CD processes

diff --git a/.github/workflows/check-quality.yml b/.github/workflows/check-quality.yml
--- a/.github/workflows/check-quality.yml
+++ b/.github/workflows/check-quality.yml
@@ -4,9 +4,15 @@ on:
   push:
     branches:
       - "**"
+    paths-ignore:
+      - "package.json"
+      - "package-lock.json"
   pull_request:
     branches:
       - "**"
+    paths-ignore:
+      - "package.json"
+      - "package-lock.json"
 
 jobs:
   check-quality:
@@ -25,8 +31,19 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Check code formatting with Prettier
+      - id: prettier_check
+        name: Check code formatting with Prettier
         run: npm run format:check
+        continue-on-error: true
 
-      - name: Check code with ESLint
+      - id: eslint_check
+        name: Check code with ESLint
         run: npm run lint
+        continue-on-error: true
+
+      - name: Fail if any check failed
+        run: |
+          if [ "${{ steps.prettier_check.outcome }}" = "failure" ] || [ "${{ steps.eslint_check.outcome }}" = "failure" ]; then
+            echo "One or more checks found issues, errors or warnings."
+            exit 1
+          fi
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,9 +1,13 @@
 name: Release
 
 on:
-  push:
+  workflow_run:
+    workflows:
+      - "CI — Push (build & test)"
+    types:
+      - completed
     branches:
-      - master
+      - "master"
 
 jobs:
   release:
@@ -14,6 +18,13 @@ jobs:
       pull-requests: write
 
     steps:
+      - name: Check CI workflow result
+        run: |
+          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
+            echo "Skipping release as the CI workflow failed. Release cannot proceed."
+            exit 1
+          fi
+
       - name: Checkout repository
         uses: actions/checkout@v4
 
